default: &default
  adapter: postgresql
  encoding: unicode
  host: db_sample_app
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: myapp_development


test:
  <<: *default
  database: myapp_test